server:
  port: 7003

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  #表示是否向eureka注册中心注册
    fetch-registry: false #自己为注册中心 为 false
    service-url:
      defaultZone: http://fwt1.com:7001/eureka/,http://fwt2.com:7002/eureka/,http://fwt3.com:7003/eureka/
