server:
  port: 8002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7003/eureka/,http://localhost:7002/eureka/
  instance:
    instance-id: springcloud-provider-dept8002