server:
  port: 8003

mybatis:
  type-aliases-package: cn.xiit.springcloud.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/java_demo?useUnicode=ture&characterEncoding=utf-8
    username: root
    password: fwt000000
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://fwt2.com:7002/eureka/,http://fwt3.com:7003/eureka/,http://fwt1.com:7001/eureka/
  instance:
    instance-id: springcloud-provider-dept8003
    hostname: localhost

info.app.name: cn-xiit-springcloud
info.company.name: xiit